const STORAGE_KEY='pentagon-work-records-v1';
const views={home:document.querySelector('#homeView'),editor:document.querySelector('#editorView'),detail:document.querySelector('#detailView'),graveyard:document.querySelector('#graveyardView')};
const outcomeOptions=[['resolved','解決した'],['faded','自然に気にならなくなった'],['nothing','何も起きなかった'],['changed','状況が変わった'],['still','まだ気になる'],['unknown','今も分からない']];
const steps=[{key:'problem',title:'気がかり・問題',help:'いま心に引っかかっていることを、まとまっていなくても大丈夫なので書いてください。',placeholder:'例：最近、仕事と自分の時間のバランスが気になる',kicker:'STEP 1'},{key:'me',title:'私の視点',help:'自分自身は、この問題についてどう感じ、何を考えていますか？',placeholder:'思いつくままに書いてみる',kicker:'STEP 2 / 6'},{key:'friend',title:'親友の視点',help:'いちばん信頼できる親友なら、どんな言葉をかけてくれそうですか？',placeholder:'親友になったつもりで書いてみる',kicker:'STEP 3 / 6'},{key:'subject',title:'対象者・対象物の視点',help:'相手や状況そのものの立場から見ると、何が見えてきますか？',placeholder:'相手・対象の立場で書いてみる',kicker:'STEP 4 / 6'},{key:'god',title:'神さまの視点',help:'より大きな視点、時間を超えた視点から見ると、どんな意味がありますか？',placeholder:'少し距離を置いて書いてみる',kicker:'STEP 5 / 6'},{key:'respected',title:'尊敬する人の視点',help:'尊敬する人なら、この問題にどう向き合うでしょうか？',placeholder:'その人の視点で書いてみる',kicker:'STEP 6 / 10'},{key:'insight',title:'気づいたこと',help:'5つの視点を通して、あらためて気づいたことを書いてください。',placeholder:'気づき・発見・変化',kicker:'STEP 7 / 10'},{key:'future',title:'今後どうなればいいか',help:'この問題が、これからどんな状態になればよさそうですか？',placeholder:'理想の状態',kicker:'STEP 8 / 10'},{key:'avoid',title:'絶対に避けたいこと',help:'これだけは避けたい、ということはありますか？',placeholder:'避けたいこと',kicker:'STEP 9 / 10'},{key:'firstStep',title:'最初の小さな一歩',help:'今日または明日からできる、いちばん小さな一歩は何ですか？',placeholder:'無理なくできる一歩',kicker:'STEP 10 / 10'}];
let current=0, draft={}, selectedId=null, deferredInstallPrompt=null;
function getRecords(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return[];const parsed=JSON.parse(raw);return Array.isArray(parsed)?parsed.filter(r=>r&&r.answers):[]}catch{return[]}}
function saveRecords(records){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(records));return true}catch{return false}}
const fmt=d=>new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium',timeStyle:'short'}).format(new Date(d));
function show(name){Object.values(views).filter(Boolean).forEach(v=>v.classList.add('hidden'));if(views[name])views[name].classList.remove('hidden');window.scrollTo(0,0)}
function renderHome(){const records=getRecords().filter(r=>!r.buried);document.querySelector('#recordCount').textContent=`${records.length}件`;const list=document.querySelector('#recordList');list.innerHTML=records.length?records.map(r=>`<article class="record-card" data-id="${r.id}"><div class="record-date">${fmt(r.createdAt)}</div><div class="record-title">${esc(r.answers.problem)||'無題の記録'}</div>${r.followUp?.status?`<div class="record-status">その後：${outcomeLabel(r.followUp.status)}</div>`:''}</article>`).join(''):'<div class="empty">まだ記録はありません。<br>最初のワークを始めてみましょう。</div>';list.querySelectorAll('[data-id]').forEach(e=>e.onclick=()=>openDetail(e.dataset.id))}
function outcomeLabel(key){return outcomeOptions.find(x=>x[0]===key)?.[1]||'未記録'}
function renderGraveyard(){const records=getRecords().filter(r=>r.buried);document.querySelector('#graveyardCount').textContent=records.length;const list=document.querySelector('#graveyardList');list.innerHTML=records.length?records.map(r=>`<article class="record-card graveyard-card" data-id="${r.id}"><div class="record-date">ワーク：${fmt(r.createdAt)}</div><div class="record-title">${esc(r.answers.problem)||'無題の記録'}</div><div class="record-status">その後：${outcomeLabel(r.followUp?.status)}</div></article>`).join(''):'<div class="empty">まだ成仏した悩みはありません。</div>';list.querySelectorAll('[data-id]').forEach(e=>e.onclick=()=>openDetail(e.dataset.id,true))}
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderStep(){const s=steps[current];document.querySelector('#progressText').textContent=`${current+1} / ${steps.length}`;document.querySelector('#progressBar').style.width=`${(current+1)/steps.length*100}%`;document.querySelector('#stepContent').innerHTML=`<p class="step-kicker">${s.kicker}</p><h2 class="step-title">${s.title}</h2><p class="step-help">${s.help}</p><label class="field-label" for="answer">回答</label><textarea id="answer" autofocus placeholder="${s.placeholder}">${esc(draft[s.key]||'')}</textarea>`;document.querySelector('#backBtn').disabled=current===0;document.querySelector('#nextBtn').textContent=current===steps.length-1?'保存する':'次へ'}
function start(){current=0;draft={};show('editor');renderStep()}
function next(){const val=document.querySelector('#answer').value.trim();if(!val){document.querySelector('#answer').focus();toast('回答を入力してください');return}draft[steps[current].key]=val;if(current<steps.length-1){current++;renderStep()}else{const records=getRecords();const record={id:crypto.randomUUID(),createdAt:new Date().toISOString(),answers:draft};records.unshift(record);saveRecords(records);renderHome();openDetail(record.id);toast('記録を保存しました')}}
function answerCard(title,key){return `<article class="answer-card"><h3>${title}</h3><p>${esc(key||'')}</p></article>`}
function openDetail(id,fromGraveyard=false){const r=getRecords().find(x=>x.id===id);if(!r)return;selectedId=id;const a=r.answers;document.querySelector('#detailBackBtn').textContent=fromGraveyard?'← 墓場に戻る':'← 一覧に戻る';document.querySelector('#detailBackBtn').dataset.fromGraveyard=fromGraveyard?'1':'';document.querySelector('#detailContent').innerHTML=`<p class="eyebrow">PENTAGON WORK / まとめ</p><h2 class="detail-title">${esc(a.problem)}</h2><p class="detail-date">${fmt(r.createdAt)}</p><div class="pentagon-map"><div class="map-box map-me"><b>私</b><span>${esc(a.me)}</span></div><div class="map-box map-friend"><b>親友</b><span>${esc(a.friend)}</span></div><div class="map-box map-subject"><b>対象者・対象物</b><span>${esc(a.subject)}</span></div><div class="map-box map-god"><b>神さま</b><span>${esc(a.god)}</span></div><div class="map-box map-respected"><b>尊敬する人</b><span>${esc(a.respected)}</span></div><div class="map-center"><small>気がかり・問題</small><strong>${esc(a.problem)}</strong></div></div><h3 class="reflection-heading">振り返り</h3><div class="reflection-grid">${answerCard('このワークで気づいたこと',a.insight)}${answerCard('今後どうなればいいか',a.future)}${answerCard('絶対に避けたいこと',a.avoid)}${answerCard('最初の小さな一歩',a.firstStep)}</div>`;renderFollowUp(r);show('detail')}
function renderFollowUp(r){const current=r.followUp?.status||'';document.querySelector('#followUpPanel').innerHTML=`<div class="follow-up-panel"><h3>その後どうなった？</h3><p class="follow-up-help">時間が経った今、この悩みは実際にはどうなりましたか？</p><select id="outcomeSelect"><option value="">結果を選択してください</option>${outcomeOptions.map(x=>`<option value="${x[0]}" ${current===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select><textarea id="followUpNote" placeholder="実際にはどうなった？（任意）">${esc(r.followUp?.note||'')}</textarea><div class="follow-up-actions"><button id="saveFollowUp" class="primary" type="button">その後を保存</button>${r.buried?'<button id="restoreBtn" class="secondary" type="button">通常の記録に戻す</button>':(current==='resolved'||current==='faded'||current==='nothing')?'<button id="buryBtn" class="secondary" type="button">この悩みを成仏させる</button>':''}</div>${r.buried?`<span class="buried-label">${fmt(r.buriedAt)}に墓場へ移動しました</span>`:''}</div>`;document.querySelector('#saveFollowUp').onclick=saveFollowUp;document.querySelector('#buryBtn')?.addEventListener('click',()=>moveToGraveyard(true));document.querySelector('#restoreBtn')?.addEventListener('click',()=>moveToGraveyard(false))}
function updateSelected(fn){const records=getRecords();const r=records.find(x=>x.id===selectedId);if(!r)return;fn(r);saveRecords(records);return r}
function saveFollowUp(){const status=document.querySelector('#outcomeSelect').value;if(!status){toast('結果を選択してください');return}const r=updateSelected(r=>r.followUp={status,note:document.querySelector('#followUpNote').value.trim(),updatedAt:new Date().toISOString()});renderFollowUp(r);renderHome();toast('その後の記録を保存しました')}
function moveToGraveyard(bury){updateSelected(r=>{r.buried=bury;if(bury)r.buriedAt=new Date().toISOString();else delete r.buriedAt});renderHome();renderGraveyard();openDetail(selectedId,bury);toast(bury?'悩みを墓場へ移しました':'通常の記録に戻しました')}
function toast(t){const e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
document.querySelector('#newWorkBtn')?.addEventListener('click',start);document.querySelector('#graveyardBtn')?.addEventListener('click',()=>{renderGraveyard();show('graveyard')});document.querySelector('#graveyardBackBtn')?.addEventListener('click',()=>{renderHome();show('home')});document.querySelector('#nextBtn')?.addEventListener('click',next);document.querySelector('#backBtn')?.addEventListener('click',()=>{if(current>0){draft[steps[current].key]=document.querySelector('#answer').value;current--;renderStep()}});document.querySelector('#detailBackBtn')?.addEventListener('click',()=>{if(document.querySelector('#detailBackBtn').dataset.fromGraveyard){renderGraveyard();show('graveyard')}else{renderHome();show('home')}});document.querySelector('#deleteBtn')?.addEventListener('click',()=>{if(confirm('この記録を削除しますか？')){saveRecords(getRecords().filter(r=>r.id!==selectedId));renderHome();show('home');toast('記録を削除しました')}});
document.querySelector('#privacyToggle')?.addEventListener('click',()=>{document.body.classList.toggle('privacy');const button=document.querySelector('#privacyToggle');if(button)button.textContent=document.body.classList.contains('privacy')?'表示':'隠す'});
document.querySelector('#exportBtn')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),records:getRecords()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`pentagon-work-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('バックアップを書き出しました')});
document.querySelector('#importInput')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data.records))throw Error();saveRecords([...data.records,...getRecords()].filter((r,i,a)=>a.findIndex(x=>x.id===r.id)===i));renderHome();toast('バックアップを読み込みました')}catch{toast('読み込めないファイルです')}};reader.readAsText(f)});
renderHome();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}))}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;document.querySelector('#installBanner')?.classList.remove('hidden')});
document.querySelector('#installBtn')?.addEventListener('click',async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;document.querySelector('#installBanner')?.classList.add('hidden')});
document.querySelector('#dismissInstall')?.addEventListener('click',()=>document.querySelector('#installBanner')?.classList.add('hidden'));
window.addEventListener('appinstalled',()=>document.querySelector('#installBanner').classList.add('hidden'));

