const STORAGE_KEY='pentagon-work-records-v1';
const views={home:document.querySelector('#homeView'),editor:document.querySelector('#editorView'),detail:document.querySelector('#detailView')};
const steps=[{key:'problem',title:'気がかり・問題',help:'いま心に引っかかっていることを、まとまっていなくても大丈夫なので書いてください。',placeholder:'例：最近、仕事と自分の時間のバランスが気になる',kicker:'STEP 1'},{key:'me',title:'私の視点',help:'自分自身は、この問題についてどう感じ、何を考えていますか？',placeholder:'思いつくままに書いてみる',kicker:'STEP 2 / 6'},{key:'friend',title:'親友の視点',help:'いちばん信頼できる親友なら、どんな言葉をかけてくれそうですか？',placeholder:'親友になったつもりで書いてみる',kicker:'STEP 3 / 6'},{key:'subject',title:'対象者・対象物の視点',help:'相手や状況そのものの立場から見ると、何が見えてきますか？',placeholder:'相手・対象の立場で書いてみる',kicker:'STEP 4 / 6'},{key:'god',title:'神さまの視点',help:'より大きな視点、時間を超えた視点から見ると、どんな意味がありますか？',placeholder:'少し距離を置いて書いてみる',kicker:'STEP 5 / 6'},{key:'respected',title:'尊敬する人の視点',help:'尊敬する人なら、この問題にどう向き合うでしょうか？',placeholder:'その人の視点で書いてみる',kicker:'STEP 6 / 10'},{key:'insight',title:'気づいたこと',help:'5つの視点を通して、あらためて気づいたことを書いてください。',placeholder:'気づき・発見・変化',kicker:'STEP 7 / 10'},{key:'future',title:'今後どうなればいいか',help:'この問題が、これからどんな状態になればよさそうですか？',placeholder:'理想の状態',kicker:'STEP 8 / 10'},{key:'avoid',title:'絶対に避けたいこと',help:'これだけは避けたい、ということはありますか？',placeholder:'避けたいこと',kicker:'STEP 9 / 10'},{key:'firstStep',title:'最初の小さな一歩',help:'今日または明日からできる、いちばん小さな一歩は何ですか？',placeholder:'無理なくできる一歩',kicker:'STEP 10 / 10'}];
let current=0, draft={}, selectedId=null;
const getRecords=()=>JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]'); const saveRecords=x=>localStorage.setItem(STORAGE_KEY,JSON.stringify(x));
const fmt=d=>new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium',timeStyle:'short'}).format(new Date(d));
function show(name){Object.values(views).forEach(v=>v.classList.add('hidden'));views[name].classList.remove('hidden');window.scrollTo(0,0)}
function renderHome(){const records=getRecords();document.querySelector('#recordCount').textContent=`${records.length}件`;const list=document.querySelector('#recordList');list.innerHTML=records.length?records.map(r=>`<article class="record-card" data-id="${r.id}"><div class="record-date">${fmt(r.createdAt)}</div><div class="record-title">${esc(r.answers.problem)||'無題の記録'}</div></article>`).join(''):'<div class="empty">まだ記録はありません。<br>最初のワークを始めてみましょう。</div>';list.querySelectorAll('[data-id]').forEach(e=>e.onclick=()=>openDetail(e.dataset.id))}
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderStep(){const s=steps[current];document.querySelector('#progressText').textContent=`${current+1} / ${steps.length}`;document.querySelector('#progressBar').style.width=`${(current+1)/steps.length*100}%`;document.querySelector('#stepContent').innerHTML=`<p class="step-kicker">${s.kicker}</p><h2 class="step-title">${s.title}</h2><p class="step-help">${s.help}</p><label class="field-label" for="answer">回答</label><textarea id="answer" autofocus placeholder="${s.placeholder}">${esc(draft[s.key]||'')}</textarea>`;document.querySelector('#backBtn').disabled=current===0;document.querySelector('#nextBtn').textContent=current===steps.length-1?'保存する':'次へ'}
function start(){current=0;draft={};show('editor');renderStep()}
function next(){const val=document.querySelector('#answer').value.trim();if(!val){document.querySelector('#answer').focus();toast('回答を入力してください');return}draft[steps[current].key]=val;if(current<steps.length-1){current++;renderStep()}else{const records=getRecords();records.unshift({id:crypto.randomUUID(),createdAt:new Date().toISOString(),answers:draft});saveRecords(records);renderHome();show('home');toast('記録を保存しました')}}
function openDetail(id){const r=getRecords().find(x=>x.id===id);if(!r)return;selectedId=id;document.querySelector('#detailContent').innerHTML=`<p class="eyebrow">PENTAGON WORK</p><h2 class="detail-title">${esc(r.answers.problem)}</h2><p class="detail-date">${fmt(r.createdAt)}</p>${steps.slice(1).map(s=>`<article class="answer-card"><h3>${s.title}</h3><p>${esc(r.answers[s.key]||'')}</p></article>`).join('')}`;show('detail')}
function toast(t){const e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
document.querySelector('#newWorkBtn').onclick=start;document.querySelector('#nextBtn').onclick=next;document.querySelector('#backBtn').onclick=()=>{if(current>0){draft[steps[current].key]=document.querySelector('#answer').value;current--;renderStep()}};document.querySelector('#detailBackBtn').onclick=()=>{renderHome();show('home')};document.querySelector('#deleteBtn').onclick=()=>{if(confirm('この記録を削除しますか？')){saveRecords(getRecords().filter(r=>r.id!==selectedId));renderHome();show('home');toast('記録を削除しました')}};
document.querySelector('#privacyToggle').onclick=()=>{document.body.classList.toggle('privacy');document.querySelector('#privacyToggle').textContent=document.body.classList.contains('privacy')?'表示':'隠す'};
document.querySelector('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),records:getRecords()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`pentagon-work-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('バックアップを書き出しました')};
document.querySelector('#importInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data.records))throw Error();saveRecords([...data.records,...getRecords()].filter((r,i,a)=>a.findIndex(x=>x.id===r.id)===i));renderHome();toast('バックアップを読み込みました')}catch{toast('読み込めないファイルです')}};reader.readAsText(f)};
renderHome();

